version: '3.4'

services:
  products:
    image: alizakaria/products:v2
    deploy:
      replicas: 2
    depends_on:
      - mssql
      - redis
    environment:
      - ConnectionStrings__DefaultConnection=Server=mssql;Database=DockerProduct;User ID=sa;Password=YourStrong@Pass;encrypt=False;
      - ConnectionStrings__Redis=redis-cache
      - IsRedisEnabled=true
      - FileUrl=http://localhost:3000/uploads/
      - FilePath=/app/uploads/
      - FrontEndUrl=http://localhost:8090
    networks:
      - product-network
    volumes:
      - uploads:/app/uploads

  productsui:
     image: alizakaria/productsui:v5
     deploy:
      replicas: 1
     depends_on:
      - products
     environment:
      - REACT_APP_API_URL=http://localhost:3000/api/
     ports:
      - "8090:3000"
     networks:
      - product-network

  mssql:
    image: alizakaria/productsdb:v5
    container_name: mssql
    environment:
      SA_PASSWORD: "YourStrong@Pass"
      ACCEPT_EULA: "Y"
    ports:
      - "4000:1433"
    networks:
      - product-network
    volumes:
      - mssql-data:/var/opt/mssql

  redis:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "4040:6379"
    networks:
      - product-network
    volumes:
      - redis-data:/data
  nginx:
    image: alizakaria/nginxproduct:v1
    container_name: nginx
    ports:
      - "3000:80"
    volumes:
      - uploads:/app/uploads
    depends_on:
      - products
    networks:
      - product-network
networks:
  product-network:

volumes:
  mssql-data:
  redis-data:
  nginx-data:
  uploads:  